insert into plants (id, name, latin, category, note, health, image_path) values
(1, 'Echeveria', 'Echeveria sp.', 'Succulenta', 'Bellissima rosetta blu-verde con punte rossastre. Stelo fiorale arancione visibile.', 'ok', '/images/plants/plant_01.jpg'),
(2, 'Pilea (Pianta del denaro cinese)', 'Pilea peperomioides', 'Ornamentale', 'Foglie tonde su lunghi piccioli rosati, con piccoli fiori rosa. Caratteristica inconfondibile.', 'ok', '/images/plants/plant_02.jpg'),
(3, 'Dracena compatta', 'Dracaena sp.', 'Ornamentale', 'Foglie allungate verde scuro con bordi arrotondati. Alcuni bordi secchi visibili.', 'warn', '/images/plants/plant_03.jpg'),
(4, 'Crassula / Portulacaria', 'Crassula ovata o Portulacaria afra', 'Succulenta', 'Foglioline tonde e carnose verdi su fusti legnosi. Più esemplari visibili.', 'ok', '/images/plants/plant_04.jpg'),
(5, 'Crassula strisciante', 'Crassula rupestris o Sedum sp.', 'Succulenta', 'Rami lunghi legnosi con foglioline piccole. Portamento ricadente tipico.', 'ok', '/images/plants/plant_05.jpg'),
(6, 'Aloe / Asparagus (da confermare)', 'Aloe sp. o Asparagus sp.', 'Succulenta / Ornamentale', 'Foglie strette cilindriche. Potrebbero essere Aloe giovane, Asparagus o Agapanthus.', 'ok', '/images/plants/plant_06.jpg'),
(7, 'Falangio (Pianta ragno)', 'Chlorophytum comosum', 'Ornamentale', 'Foglie strette con striscia bianca centrale. Classica pianta ragno.', 'ok', '/images/plants/plant_07.jpg'),
(8, 'Cactus colonnare peloso + Opuntia', 'Cephalocereus senilis + Opuntia sp.', 'Cactus', 'Il cactus alto coperto di lunghi peli bianchi è il Vecchio del Messico. Accanto c''è un cactus ficodindia.', 'ok', '/images/plants/plant_08.jpg'),
(9, 'Opuntia + Tradescantia', 'Opuntia microdasys + Tradescantia sp.', 'Cactus / Ornamentale', 'Cladodi tondi a forma di orecchie di coniglio. A sinistra Tradescantia bicolore lilla/argento.', 'ok', '/images/plants/plant_09.jpg'),
(10, 'Aloe / Asparagus adulto', 'Aloe sp.', 'Succulenta', 'Foglie lunghe cilindriche verde brillante con spine. Portamento cespuglioso.', 'ok', '/images/plants/plant_10.jpg'),
(11, 'Asparagus + Kalanchoe', 'Asparagus sp. + Kalanchoe sp.', 'Ornamentale / Succulenta', 'In alto: Asparagus con foglioline ad aghetto. In basso: grande foglia con bordo rosso ondulato (Kalanchoe).', 'ok', '/images/plants/plant_11.jpg'),
(12, 'Opuntia + Tradescantia', 'Opuntia sp. + Tradescantia sp.', 'Cactus / Ornamentale', 'Cactus ficodindia con cladodi grandi. A destra Tradescantia con foglie bicolori.', 'ok', '/images/plants/plant_12.jpg'),
(13, 'Kalanchoe', 'Kalanchoe luciae o thyrsiflora', 'Succulenta', 'Grandi foglie rotonde verde brillante con margine rosso-rosa ondulato. Molto ornamentale.', 'ok', '/images/plants/plant_13.jpg'),
(14, 'Mammillaria / Cactus piccolo', 'Mammillaria sp.', 'Cactus', 'Piccolo cactus cilindrico in vasetto con tubercoli rotondi.', 'ok', '/images/plants/plant_14.jpg'),
(15, 'Crassula ovata (Pianta di giada)', 'Crassula ovata', 'Succulenta', 'Bel cespo con foglioline tonde e carnose verdi su rami legnosi. Molto sviluppata.', 'ok', '/images/plants/plant_15.jpg'),
(16, 'Calibrachoa', 'Calibrachoa sp.', 'Fioritura', 'Moltissimi fiorellini lilla-viola con macchia scura centrale.', 'ok', '/images/plants/plant_16.jpg'),
(17, 'Petunia', 'Petunia sp.', 'Fioritura', 'Fiori grandi viola intenso a imbuto. Classica petunia da balcone.', 'ok', '/images/plants/plant_17.jpg'),
(18, 'Limone (spoglio)', 'Citrus limon', 'Albero da frutto', 'Pianta di limone che ha perso tutte le foglie. Potatura drastica o stress idrico. I fusti sono ancora vivi.', 'ok', '/images/plants/plant_18.jpg'),
(19, 'Opuntia grande', 'Opuntia sp.', 'Cactus', 'Cactus ficodindia con cladodi tondi viola-verdi. Esemplare bello e ben sviluppato.', 'ok', '/images/plants/plant_19.jpg'),
(20, 'Gelsomino rampicante', 'Trachelospermum jasminoides', 'Rampicante', 'Rampicante con fiori stellati bianchi. Ancora con etichetta. Profumatissimo!', 'ok', '/images/plants/plant_20.jpg'),
(21, 'Lavanda / Bulbi in germoglio', 'da confermare', 'Aromatica / Ornamentale', 'Ciuffi di foglioline verdi strette. Potrebbe essere lavanda giovane o bulbi in germoglio.', 'ok', '/images/plants/plant_21.jpg'),
(22, 'Olivo in fioritura', 'Olea europaea', 'Albero da frutto', 'Foglie verde-giallastre con piccoli grappoli fiorali. Alcune foglie ingiallite: possibile carenza nutritiva.', 'warn', '/images/plants/plant_22.jpg'),
(23, 'Olivo giovane (piena fioritura)', 'Olea europaea', 'Albero da frutto', 'Giovane olivo coperto di infiorescenze bianche. Ottima salute!', 'ok', '/images/plants/plant_23.jpg'),
(24, 'Falangio adulto', 'Chlorophytum comosum', 'Ornamentale', 'Esemplare adulto e rigoglioso con lungo stelo fiorale.', 'ok', '/images/plants/plant_24.jpg'),
(25, 'Kalanchoe + Crassula', 'Kalanchoe sp. + Crassula sp.', 'Succulenta', 'Vaso giallo con due succulente: grandi foglie con bordo rosso (Kalanchoe) e foglioline tonde (Crassula).', 'ok', '/images/plants/plant_25.jpg'),
(26, 'Banana ornamentale + Tradescantia', 'Musa sp. + Tradescantia zebrina', 'Ornamentale', 'Grande pianta di banana con foglie ampie. Davanti, Tradescantia in fioritura con fiori viola.', 'ok', '/images/plants/plant_26.jpg'),
(27, 'Yucca', 'Yucca elephantipes o sp.', 'Ornamentale', 'Foglie lunghe rigide e appuntite in rosetta. Portamento tipico della Yucca.', 'ok', '/images/plants/plant_27.jpg'),
(28, 'Agave', 'Agave sp.', 'Succulenta', 'Rosetta di foglie rigide verde-glauco con margini chiari.', 'ok', '/images/plants/plant_28.jpg'),
(29, 'Agave grande', 'Agave americana', 'Succulenta', 'Esemplare molto maturo con foglie azzurro-violacee. Probabile Agave americana.', 'ok', '/images/plants/plant_29.jpg'),
(30, 'Limone / Agrume', 'Citrus limon o sp.', 'Albero da frutto', 'Foglie lucide tipiche degli agrumi e piccoli fiori bianchi in formazione.', 'ok', '/images/plants/plant_30.jpg'),
(31, 'Aloe variegata', 'Aloe aristata o variegata', 'Succulenta', 'Aloe con caratteristiche macchie bianche sulle foglie e spine morbide.', 'ok', '/images/plants/plant_31.jpg'),
(32, 'Agave / Aloe grande', 'Agave o Aloe sp.', 'Succulenta', 'Rosetta di foglie ampie dentate. Potrebbe essere Aloe o Agave giovane.', 'ok', '/images/plants/plant_32.jpg'),
(33, 'Gelsomino (secondo)', 'Trachelospermum jasminoides', 'Rampicante', 'Secondo rampicante con fiori stellati bianchi ed etichetta. In fase di attecchimento.', 'ok', '/images/plants/plant_33.jpg'),
(34, 'Mirto', 'Myrtus communis', 'Arbusto mediterraneo', 'Arbusto con foglie piccole ovali lucide verde scuro. Tipicamente mediterraneo.', 'ok', '/images/plants/plant_34.jpg'),
(35, 'Basilico', 'Ocimum basilicum', 'Aromatica', 'Numerosi cespi giovani in cassettiera nera. Ottima produzione!', 'ok', '/images/plants/plant_35.jpg'),
(36, 'Salvia', 'Salvia officinalis', 'Aromatica', 'Foglie vellutate grigio-verdi tipiche della salvia. Piante abbondanti e sane.', 'ok', '/images/plants/plant_36.jpg'),
(37, 'Alloro', 'Laurus nobilis', 'Aromatica / Arbusto', 'Foglie allungate lucide. Alcune ingiallite: possibile carenza di azoto o ferro.', 'warn', '/images/plants/plant_37.jpg'),
(38, 'Timo in fioritura', 'Thymus vulgaris', 'Aromatica', 'Piena fioritura con fiorellini rosa-lilla. Segno di ottima salute!', 'ok', '/images/plants/plant_38.jpg'),
(39, 'Origano', 'Origanum vulgare', 'Aromatica', 'Foltissimo e rigoglioso. Foglioline tonde tipiche dell''origano.', 'ok', '/images/plants/plant_39.jpg'),
(40, 'Senecio / Kleinia (da confermare)', 'Senecio mandraliscae o sp.', 'Succulenta', 'Foglie lunghe e carnose verde-glauco con riflessi gialli. Succulenta ornamentale.', 'ok', '/images/plants/plant_40.jpg'),
(41, 'Pelargonio odoroso (Geranio)', 'Pelargonium graveolens', 'Aromatica / Ornamentale', 'Foglie lobate profumate tipiche del geranio odoroso. Con supporto circolare verde.', 'ok', '/images/plants/plant_41.jpg'),
(42, 'Pomodoro (in frutto)', 'Solanum lycopersicum', 'Ortaggio', 'Pianta matura con pomodorini verdi e fiori gialli. Foglie scure e raggrinzite: possibile peronospora.', 'bad', '/images/plants/plant_42.jpg'),
(43, 'Pomodoro (piantina)', 'Solanum lycopersicum', 'Ortaggio', 'Piantina giovane appena trapiantata. In fase di attecchimento.', 'ok', '/images/plants/plant_43.jpg'),
(44, 'Menta', 'Mentha sp.', 'Aromatica', 'Foglie accartocciate e bollose: attacco di afidi o ragnetto rosso. Trattare urgentemente!', 'bad', '/images/plants/plant_44.jpg'),
(45, 'Rosmarino', 'Salvia rosmarinus', 'Aromatica', 'Grande cespuglio maturo con aghi fitti. In basso si vede anche un pelargonio.', 'ok', '/images/plants/plant_45.jpg')
on conflict (id) do nothing;
